services:
  - type: web
    name: arequipa-market
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn drfarequipamarket.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: drfarequipamarket.settings.production
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    disk:
      name: media
      mountPath: /app/media
      sizeGB: 1 