# Generated by Django 5.1.3 on 2025-06-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_departamento_district_province_product_departamento_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorite_products', to='product.product'),
        ),
    ]
