# Generated by Django 5.1.3 on 2025-05-16 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alternative_text", models.CharField(max_length=100)),
                ("url", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "Dólares"), ("PEN", "Soles")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NEW", "Nuevo - nunca usado"),
                            ("USED/A", "Usado - como nuevo"),
                            ("USED/B", "Usado - bueno"),
                            ("USED/C", "Usado - bastante"),
                        ],
                        max_length=6,
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
        ),
    ]
