# Generated by Django 5.1.3 on 2025-06-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='departamento',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products_in_departamento',
                to='product.departamento'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='province',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products_in_province',
                to='product.province'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='district',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products_in_district',
                to='product.district'
            ),
        ),
    ] 