# Generated by Django 5.1.3 on 2025-05-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_chat_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="alternative_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.ImageField(upload_to="product_images/"),
        ),
    ]
