# Generated by Django 5.1.3 on 2025-06-04 08:32

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_productimage_alternative_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.ImageField(
                storage=storages.backends.s3.S3Storage(), upload_to="product_images/"
            ),
        ),
    ]
